// Generates lib/src/native/abi_generated.dart from the C++ ABI offset locks.
//
// The C++ side is the single source of truth: every FFI struct field is
// pinned with `COMMAND_EXPORT_ABI_OFFSET(Struct, field, N)` (a compiler-verified
// `static_assert(offsetof(...) == N)`) plus a `sizeof(Struct) == N` assert.
// This tool parses those lines and emits matching Dart constants, so the
// Dart-side offsets can never silently drift from the C++ struct.
//
// Regenerate after changing any exported struct:
//   dart run tool/gen_abi.dart
//
// A staleness guard in test/abi_generated_test.dart fails CI if the
// committed abi_generated.dart no longer matches the C++ headers.

import 'dart:io';

/// One C++ struct to mirror into a Dart class.
class _StructSpec {
  final String file; // path relative to repo root
  final String cppName; // struct name in C++
  final String dartClass; // generated Dart class name
  const _StructSpec(this.file, this.cppName, this.dartClass);
}

const _specs = <_StructSpec>[
  _StructSpec(
    'vendor/maplibre-native/include/mbgl/command_export/draw_command.hpp',
    'DrawCommand',
    'DrawCommandAbi',
  ),
  _StructSpec('native/src/bridge_labels.cpp', 'LabelExport', 'LabelExportAbi'),
];

const _outputPath = 'lib/src/native/abi_generated.dart';

/// Builds the full generated Dart source. Pure function (reads the C++
/// files, returns text) so the staleness test can compare without writing.
String generateAbiDart() {
  final buf = StringBuffer();
  buf.writeln('// GENERATED by tool/gen_abi.dart — do NOT edit by hand.');
  buf.writeln('// Regenerate: dart run tool/gen_abi.dart');
  buf.writeln('//');
  buf.writeln(
    '// Byte offsets are mirrored from the C++ COMMAND_EXPORT_ABI_OFFSET locks,',
  );
  buf.writeln('// which the compiler verifies against the real struct layout.');
  buf.writeln('// Sources:');
  for (final s in _specs) {
    buf.writeln('//   ${s.file} (${s.cppName})');
  }

  for (final spec in _specs) {
    final text = File(spec.file).readAsStringSync();
    final size = _parseSize(text, spec.cppName, spec.file);
    final offsets = _parseOffsets(text, spec.cppName, spec.file);

    buf.writeln();
    buf.writeln('/// Byte offsets of C++ `${spec.cppName}` (size $size).');
    buf.writeln('abstract final class ${spec.dartClass} {');
    buf.writeln('  ${spec.dartClass}._();');
    buf.writeln('  static const int size = $size;');
    for (final e in offsets) {
      buf.writeln('  static const int ${e.key} = ${e.value};');
    }
    buf.writeln('}');
  }
  return buf.toString();
}

int _parseSize(String text, String struct, String file) {
  final re = RegExp('sizeof\\(\\s*$struct\\s*\\)\\s*==\\s*(\\d+)');
  final m = re.firstMatch(text);
  if (m == null) {
    throw StateError('No `sizeof($struct) == N` assert found in $file');
  }
  return int.parse(m.group(1)!);
}

/// Returns (field, offset) pairs in source order.
List<MapEntry<String, int>> _parseOffsets(
  String text,
  String struct,
  String file,
) {
  // COMMAND_EXPORT_ABI_OFFSET(Struct, field, 123)  — the macro definition line uses a
  // non-numeric third arg (`off`) and is skipped by the \d+ requirement.
  final re = RegExp(
    'COMMAND_EXPORT_ABI_OFFSET\\(\\s*$struct\\s*,\\s*(\\w+)\\s*,\\s*(\\d+)\\s*\\)',
  );
  final out = <MapEntry<String, int>>[];
  final seen = <String>{};
  for (final m in re.allMatches(text)) {
    final field = m.group(1)!;
    if (!seen.add(field)) continue; // guard against accidental duplicates
    out.add(MapEntry(field, int.parse(m.group(2)!)));
  }
  if (out.isEmpty) {
    throw StateError(
      'No COMMAND_EXPORT_ABI_OFFSET($struct, ...) locks found in $file',
    );
  }
  return out;
}

void main() {
  final generated = generateAbiDart();
  File(_outputPath).writeAsStringSync(generated);
  stdout.writeln('Wrote $_outputPath');
}
