# Portable MapLibre platform sources shared by Linux and Windows.
function(maplibre_fluttergpu_add_default_sources target maplibre_source_dir)
    target_sources(
        ${target}
        PRIVATE
            ${maplibre_source_dir}/platform/default/src/mln/gfx/headless_backend.cpp
            ${maplibre_source_dir}/platform/default/src/mln/gfx/headless_frontend.cpp
            ${maplibre_source_dir}/platform/default/src/mln/command_export/headless_backend.cpp
            ${maplibre_source_dir}/platform/default/src/mln/i18n/collator.cpp
            ${maplibre_source_dir}/platform/default/src/mln/i18n/number_format.cpp
            ${maplibre_source_dir}/platform/default/src/mln/layermanager/layer_manager.cpp
            ${maplibre_source_dir}/platform/default/src/mln/platform/time.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/asset_file_source.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/database_file_source.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/file_source_manager.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/file_source_request.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/http_file_source.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/local_file_request.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/local_file_source.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/mbtiles_file_source.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/main_resource_loader.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/offline.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/offline_database.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/offline_download.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/online_file_source.cpp
            ${maplibre_source_dir}/platform/default/src/mln/storage/$<IF:$<BOOL:${MLN_WITH_PMTILES}>,pmtiles_file_source.cpp,pmtiles_file_source_stub.cpp>
            ${maplibre_source_dir}/platform/default/src/mln/storage/sqlite3.cpp
            ${maplibre_source_dir}/platform/default/src/mln/text/bidi.cpp
            ${maplibre_source_dir}/platform/default/src/mln/text/local_glyph_rasterizer.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/async_task.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/compression.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/filesystem.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/i18n.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/image.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/jpeg_reader.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/webp_reader.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/logging_stderr.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/monotonic_timer.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/png_reader.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/png_writer.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/run_loop.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/string_stdlib.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/timer.cpp
            ${maplibre_source_dir}/platform/default/src/mln/util/utf.cpp
    )
endfunction()
