// Binary label records and flags shared with Dart FFI decoders.
#pragma once

#if MLN_RENDER_BACKEND_COMMAND_EXPORT

#include <cstdint>

#include <mbgl/command_export/draw_command.hpp>

namespace maplibre_bridge::labels {

constexpr uint32_t kTextPlaced = 1u << 0;
constexpr uint32_t kIconPlaced = 1u << 1;
constexpr uint32_t kTextAlongLine = 1u << 2;
constexpr uint32_t kIconAlongLine = 1u << 3;

constexpr uint32_t kVertical = 1u << 0;
constexpr uint32_t kIconSDF = 1u << 1;
constexpr uint32_t kTextPitchMap = 1u << 2;
constexpr uint32_t kTextRotationMap = 1u << 3;
constexpr uint32_t kIconPitchMap = 1u << 4;
constexpr uint32_t kIconRotationMap = 1u << 5;
constexpr uint32_t kTextKeepUpright = 1u << 6;
constexpr uint32_t kIconKeepUpright = 1u << 7;
constexpr uint32_t kTextRTL = 1u << 8;

constexpr uint32_t kSectionHasColor = 1u << 0;
constexpr uint32_t kSectionHasImage = 1u << 1;

struct LabelStringRefExport {
    uint32_t offset;
    uint32_t length;
};
static_assert(sizeof(LabelStringRefExport) == 8, "LabelStringRefExport size must be stable for FFI");
COMMAND_EXPORT_ABI_OFFSET(LabelStringRefExport, offset, 0);
COMMAND_EXPORT_ABI_OFFSET(LabelStringRefExport, length, 4);

struct LabelTextSectionExport {
    uint32_t start;
    uint32_t end;
    float fontScale;
    uint32_t flags;
    float colorR;
    float colorG;
    float colorB;
    float colorA;
    uint32_t fontsOffset;
    uint32_t fontCount;
    uint32_t imageOffset;
    uint32_t imageLength;
};
static_assert(sizeof(LabelTextSectionExport) == 48, "LabelTextSectionExport size must be stable for FFI");
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, start, 0);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, end, 4);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, fontScale, 8);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, flags, 12);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, colorR, 16);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, colorG, 20);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, colorB, 24);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, colorA, 28);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, fontsOffset, 32);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, fontCount, 36);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, imageOffset, 40);
COMMAND_EXPORT_ABI_OFFSET(LabelTextSectionExport, imageLength, 44);

struct LabelPathPointExport {
    float x;
    float y;
};
static_assert(sizeof(LabelPathPointExport) == 8, "LabelPathPointExport size must be stable for FFI");
COMMAND_EXPORT_ABI_OFFSET(LabelPathPointExport, x, 0);
COMMAND_EXPORT_ABI_OFFSET(LabelPathPointExport, y, 4);

// Variable-size values use byte offsets into the session-owned label blob.
struct LabelExport {
    double lat;
    double lon;
    double iconLat;
    double iconLon;
    float fontSize;
    float textR;
    float textG;
    float textB;
    float textA;
    float haloR;
    float haloG;
    float haloB;
    float haloA;
    float haloWidth;
    float textW;
    float textH;
    float iconW;
    float iconH;
    float iconSize;
    float iconOpacity;
    float iconR;
    float iconG;
    float iconB;
    float iconA;
    uint32_t flags;
    float textAngle;
    uint32_t crossTileID;
    uint32_t textOffset;
    uint32_t textLength;
    uint32_t layerOffset;
    uint32_t layerLength;
    uint32_t iconOffset;
    uint32_t iconLength;
    uint32_t textFontsOffset;
    uint32_t textFontCount;
    uint32_t textSectionsOffset;
    uint32_t textSectionCount;
    uint32_t textPathOffset;
    uint32_t textPathCount;
    uint32_t iconPathOffset;
    uint32_t iconPathCount;
    float textOffsetX;
    float textOffsetY;
    float iconOffsetX;
    float iconOffsetY;
    float textOpacity;
    float haloBlur;
    float letterSpacing;
    float lineHeight;
    float maxWidth;
    float iconAngle;
    float textRotation;
    float iconRotation;
    float textTranslateX;
    float textTranslateY;
    float iconTranslateX;
    float iconTranslateY;
    float iconHaloR;
    float iconHaloG;
    float iconHaloB;
    float iconHaloA;
    float iconHaloWidth;
    float iconHaloBlur;
    float iconFitWidth;
    float iconFitHeight;
    float textTransformXX;
    float textTransformXY;
    float textTransformYX;
    float textTransformYY;
    float iconTransformXX;
    float iconTransformXY;
    float iconTransformYX;
    float iconTransformYY;
    int32_t layerIndex;
    uint32_t styleFlags;
    uint32_t textJustify;
    uint32_t renderGroup;
    uint32_t renderOrder;
    uint32_t logicalTextOffset;
    uint32_t logicalTextLength;
    uint32_t visualTextSectionsOffset;
    uint32_t visualTextSectionCount;
    int32_t tileWrap;
};
static_assert(sizeof(LabelExport) == 352, "LabelExport size must be stable for FFI");

COMMAND_EXPORT_ABI_OFFSET(LabelExport, lat, 0);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, lon, 8);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconLat, 16);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconLon, 24);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, fontSize, 32);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textR, 36);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textG, 40);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textB, 44);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textA, 48);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, haloR, 52);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, haloG, 56);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, haloB, 60);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, haloA, 64);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, haloWidth, 68);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textW, 72);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textH, 76);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconW, 80);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconH, 84);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconSize, 88);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconOpacity, 92);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconR, 96);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconG, 100);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconB, 104);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconA, 108);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, flags, 112);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textAngle, 116);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, crossTileID, 120);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textOffset, 124);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textLength, 128);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, layerOffset, 132);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, layerLength, 136);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconOffset, 140);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconLength, 144);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textFontsOffset, 148);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textFontCount, 152);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textSectionsOffset, 156);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textSectionCount, 160);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textPathOffset, 164);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textPathCount, 168);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconPathOffset, 172);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconPathCount, 176);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textOffsetX, 180);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textOffsetY, 184);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconOffsetX, 188);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconOffsetY, 192);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textOpacity, 196);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, haloBlur, 200);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, letterSpacing, 204);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, lineHeight, 208);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, maxWidth, 212);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconAngle, 216);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textRotation, 220);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconRotation, 224);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textTranslateX, 228);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textTranslateY, 232);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconTranslateX, 236);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconTranslateY, 240);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconHaloR, 244);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconHaloG, 248);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconHaloB, 252);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconHaloA, 256);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconHaloWidth, 260);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconHaloBlur, 264);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconFitWidth, 268);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconFitHeight, 272);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textTransformXX, 276);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textTransformXY, 280);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textTransformYX, 284);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textTransformYY, 288);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconTransformXX, 292);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconTransformXY, 296);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconTransformYX, 300);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, iconTransformYY, 304);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, layerIndex, 308);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, styleFlags, 312);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, textJustify, 316);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, renderGroup, 320);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, renderOrder, 324);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, logicalTextOffset, 328);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, logicalTextLength, 332);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, visualTextSectionsOffset, 336);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, visualTextSectionCount, 340);
COMMAND_EXPORT_ABI_OFFSET(LabelExport, tileWrap, 344);

// Variable-size values use byte offsets into the static label blob.
struct LabelStaticExport {
    float fontSize;
    float textR;
    float textG;
    float textB;
    float textA;
    float haloR;
    float haloG;
    float haloB;
    float haloA;
    float haloWidth;
    float iconSize;
    float iconOpacity;
    float iconR;
    float iconG;
    float iconB;
    float iconA;
    uint32_t crossTileID;
    uint32_t textOffset;
    uint32_t textLength;
    uint32_t layerOffset;
    uint32_t layerLength;
    uint32_t iconOffset;
    uint32_t iconLength;
    uint32_t textFontsOffset;
    uint32_t textFontCount;
    uint32_t textSectionsOffset;
    uint32_t textSectionCount;
    float textOpacity;
    float haloBlur;
    float letterSpacing;
    float lineHeight;
    float maxWidth;
    float textRotation;
    float iconRotation;
    float iconHaloR;
    float iconHaloG;
    float iconHaloB;
    float iconHaloA;
    float iconHaloWidth;
    float iconHaloBlur;
    float iconFitWidth;
    float iconFitHeight;
    int32_t layerIndex;
    uint32_t styleFlags;
    uint32_t textJustify;
    uint32_t renderGroup;
    uint32_t logicalTextOffset;
    uint32_t logicalTextLength;
    uint32_t visualTextSectionsOffset;
    uint32_t visualTextSectionCount;
};
static_assert(sizeof(LabelStaticExport) == 200, "LabelStaticExport size must be stable for FFI");
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, fontSize, 0);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textR, 4);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textG, 8);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textB, 12);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textA, 16);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, haloR, 20);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, haloG, 24);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, haloB, 28);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, haloA, 32);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, haloWidth, 36);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconSize, 40);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconOpacity, 44);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconR, 48);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconG, 52);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconB, 56);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconA, 60);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, crossTileID, 64);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textOffset, 68);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textLength, 72);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, layerOffset, 76);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, layerLength, 80);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconOffset, 84);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconLength, 88);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textFontsOffset, 92);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textFontCount, 96);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textSectionsOffset, 100);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textSectionCount, 104);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textOpacity, 108);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, haloBlur, 112);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, letterSpacing, 116);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, lineHeight, 120);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, maxWidth, 124);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textRotation, 128);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconRotation, 132);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconHaloR, 136);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconHaloG, 140);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconHaloB, 144);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconHaloA, 148);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconHaloWidth, 152);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconHaloBlur, 156);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconFitWidth, 160);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, iconFitHeight, 164);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, layerIndex, 168);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, styleFlags, 172);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, textJustify, 176);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, renderGroup, 180);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, logicalTextOffset, 184);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, logicalTextLength, 188);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, visualTextSectionsOffset, 192);
COMMAND_EXPORT_ABI_OFFSET(LabelStaticExport, visualTextSectionCount, 196);

// Path offsets use the dynamic blob and staticIndex joins cached content.
struct LabelDynamicExport {
    double lat;
    double lon;
    double iconLat;
    double iconLon;
    float textW;
    float textH;
    float iconW;
    float iconH;
    uint32_t flags;
    float textAngle;
    uint32_t textPathOffset;
    uint32_t textPathCount;
    uint32_t iconPathOffset;
    uint32_t iconPathCount;
    float textOffsetX;
    float textOffsetY;
    float iconOffsetX;
    float iconOffsetY;
    float iconAngle;
    float textTranslateX;
    float textTranslateY;
    float iconTranslateX;
    float iconTranslateY;
    float textTransformXX;
    float textTransformXY;
    float textTransformYX;
    float textTransformYY;
    float iconTransformXX;
    float iconTransformXY;
    float iconTransformYX;
    float iconTransformYY;
    uint32_t renderOrder;
    uint32_t staticIndex;
    int32_t tileWrap;
};
static_assert(sizeof(LabelDynamicExport) == 152, "LabelDynamicExport size must be stable for FFI");
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, lat, 0);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, lon, 8);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconLat, 16);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconLon, 24);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textW, 32);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textH, 36);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconW, 40);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconH, 44);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, flags, 48);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textAngle, 52);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textPathOffset, 56);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textPathCount, 60);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconPathOffset, 64);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconPathCount, 68);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textOffsetX, 72);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textOffsetY, 76);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconOffsetX, 80);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconOffsetY, 84);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconAngle, 88);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textTranslateX, 92);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textTranslateY, 96);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconTranslateX, 100);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconTranslateY, 104);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textTransformXX, 108);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textTransformXY, 112);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textTransformYX, 116);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, textTransformYY, 120);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconTransformXX, 124);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconTransformXY, 128);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconTransformYX, 132);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, iconTransformYY, 136);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, renderOrder, 140);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, staticIndex, 144);
COMMAND_EXPORT_ABI_OFFSET(LabelDynamicExport, tileWrap, 148);

} // namespace maplibre_bridge::labels

#endif // MLN_RENDER_BACKEND_COMMAND_EXPORT
